### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by SoYoung210** [SoYoung210/real-diff#2]
해야할 것들 
(🚀: 필수, 안하면 버그남. 🥯: 옵셔널 추가기능류)

- [x] 🚀 `github.com/pulls` url이 아닐 때 api call없이 default view띄우기
> url 기반으로 가져오므로 pr 화면이 아닐 때는 에러남.

- [x] 🚀 [chrome storage](https://developer.chrome.com/extensions/storage)써서 GitHub Token값 영속적으로 관리하기
> [여기](https://github.com/SoYoung210/real-diff/tree/add-chrome-storage)에서 진행중
- [ ] 🥯 사용자가 ignore할 파일들 체크리스트로 받기
- [ ] 🥯 마크업
